// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkiAPI.Repositories;

#nullable disable

namespace SkiAPI.Migrations
{
    [DbContext(typeof(SkiDbContext))]
    [Migration("20250313235206_AddSkiModel")]
    partial class AddSkiModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkiAPI.Models.SkiBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateFounded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkiBrandId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkiBrandId");

                    b.ToTable("SkiBrands");
                });

            modelBuilder.Entity("SkiAPI.Models.SkiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkiBrandId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkiBrandId");

                    b.ToTable("SkiModel");
                });

            modelBuilder.Entity("SkiAPI.Models.SkiBrand", b =>
                {
                    b.HasOne("SkiAPI.Models.SkiBrand", null)
                        .WithMany("SkiBrands")
                        .HasForeignKey("SkiBrandId");
                });

            modelBuilder.Entity("SkiAPI.Models.SkiModel", b =>
                {
                    b.HasOne("SkiAPI.Models.SkiBrand", "SkiBrand")
                        .WithMany("SkiModels")
                        .HasForeignKey("SkiBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkiBrand");
                });

            modelBuilder.Entity("SkiAPI.Models.SkiBrand", b =>
                {
                    b.Navigation("SkiBrands");

                    b.Navigation("SkiModels");
                });
#pragma warning restore 612, 618
        }
    }
}
